# column names from 'name_basics' dataframe
nconst = 'nconst'
id_person = 'id_person'
primary_name = 'primary_name'
birth_year = 'birth_year'
death_year = 'death_year'
primary_profession = 'primary_profession'
known_for_titles = 'known_for_titles'
age = 'age'
is_alive = 'is_alive'

# column names from 'title_basics' dataframe
tconst = 'tconst'
title_type = 'title_type'
primary_type = 'primary_type'
original_title = 'original_title'
is_adult = 'is_adult'
start_year = 'start_year'
end_year = 'end_year'
runtime_minutes = 'runtime_minutes'
genres = 'genres'
